#+TITLE: Untitled Proto-Language 1
#+AUTHOR: Emmy Emmycelium
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style.css" />

* Phonology
** Consonants
The consonant inventory is as follows
#+BEGIN_EXPORT html
<table><tbody><tr class="head">
    <th></th>
    <th scope="col" colspan="2">Labial</th>
    <th scope="col" colspan="2">Alevolar</th>
    <th scope="col" colspan="2">Dorsal</th>
    <th scope="col">Uvular</th>
</tr><tr>
    <th scope="row">Nasal</th>
    <td colspan="2">m</td>
    <td colspan="2">n</td>
    <td colspan="2">ŋ</td>
    <td>(ɴ)</td>
</tr><tr>
    <th scope="row">Stop</th>
    <td>p</td>
    <td>b</td>
    <td>t</td>
    <td>d</td>
    <td>k</td>
    <td>g</td>
    <td>q</td>
</tr><tr>
    <th scope="row">Affricate</th>
    <td colspan="2"></td>
    <td>ts</td>
    <td rowspan="2">(d)z</td>
    <td colspan="2"></td>
    <td></td>
</tr><tr>
    <th scope="row">Fricative</th>
    <td colspan="2">f</td>
    <td>s</td>
    <td colspan="2">x</td>
    <td></td>
</tr><tr>
    <th scope="row">Approximant</th>
    <td colspan="2">(w)</td>
    <td colspan="2">l</td>
    <td colspan="2">(j)</td>
    <td></td>
</tr><tr>
    <th scope="row">Trill</th>
    <td colspan="2"></td>
    <td colspan="2">r</td>
    <td colspan="2"></td>
    <td></td>
</tr></tbody></table>
#+END_EXPORT

The realization of the phoneme /​dz/ varies between dialects, with some realizing it as a fricative and others as an affricate. /​f/ can be realized as either a bilabial fricative [ɸ] or a labiodental [f]. The velar consonants become palatalized before the close front vowel /​i/. The approximants [j] and [w] are allophones of the vowel phonemes /​i/ and /​u/ rather than consonant phonemes in their own right. The uvular nasal /​ɴ/ occurs only as an allophone of /​m/ before /​q/

For examples in this document, words are transcribed as they would be in ipa with the exceptions that /​ŋ/ is written as ng, /​m/ is written as n before non-labial stops, /​dz/ is written as z and /​ts/ is written as c.

** Vowels
The vowel inventory is as follows

#+BEGIN_EXPORT html
<table><tbody><tr class="head">
    <th></th>
    <th scope="col">Front</th>
    <th scope="col">Back</th>
</tr><tr>
    <th scope="row">Close</th>
    <td>i</td>
    <td>u</td>
</tr><tr>
    <th scope="row">Mid</th>
    <td>e</td>
    <td>o</td>
</tr><tr>
    <th scope="row">Open</th>
    <td colspan="2">a</td>
</tr></tbody></table>
#+END_EXPORT

As mentioned above, the close vowels /​i/ and /​u/ have glide allophones [j] and [w]. /​a/, /​e/ and /​o/ contrast with long /​aː/, /​eː/ and /​oː/ (transcribed ā, ē, ō). 

** Phonotactics
Syllables may contain an onset consonant, a medial glide, a nucleus, and a final consonant, though the only one of these positions which /must/ be filled is the nucleus.

*** Onsets
All consonants may act as the onset of a syllable, however an initial uvular stop /​q/ restricts what finals may occur. Namely, no medials may occur with this consonant and the nucleus may not be a high vowel (/​i/ or /​u/).

*** Finals
Finals maximally consist of a medial, a nucleus, and a coda consonant. For most syllables, the nucleus will be one of the 5 short vowels. The medial may then be either /​i/ or /​u/, with the restriction that front medials may not occur with front vowels and back medials may not occur with back vowels (e.g. */je/ is not an allowed final). The coda consonant may be /​p/, /​t/, /​k/, /​m/ or /​r/. Note that while the nasal coda is transcribed as /​m/ and this is its realization in isolation, within the context of a longer utterance it will harmonize to the place of articulation of the following consonant. Therefore a word such as rm-da "of animal fats" will become rnda

For syllables with a long vowel as the nucleus, there cannot be both a medial and a coda and only the stop codas can occur.

There are also syllables which have a syllabic consonant, either /​r/ or /​m/, as their nucleus instead of a vowel. These syllables never have a medial or a coda, and just as with coda /​m/, the syllabic /​m/ as nucleus will harmonize with the following consonant. 

*** Strong and Weak syllables
Syllables which contain a long vowel, have a medial and a short vowel, or have an  /​r/ or /​m/ coda are considered "strong", while other syllables are considered "weak". 

In some contexts, strong syllables may undergo weakening. When a syllable with a long vowel weakens, the vowel shortens. For those with a short vowel and a medial, the short vowel drops out and the medial glide becomes a vowel. Lastly, for those with an /​r/ or /​m/ coda, the vowel drops out and the coda becomes the nucleus.

Similarly, weak syllables may sometimes undergo strengthening. For syllables with a short /​a/, /​e/ or /​o/ as the nucleus, the vowel lengthens. For those with /​i/ or /​u/ as the nucleus, an /​a/ is inserted after, making the former nucleus into a medial. For those with syllabic /​r/ or /​m/, an /​a/ is inserted before, making the nucleus into a coda.

In inflection tables throughout the rest of this document, red cells indicate forms for which the final syllable should be weakened, and green cells indicate those for which it should be strengthened.

* Inflectional Morphology
** Nouns
Most nouns inflect for 2 numbers (singular and plural) and 3 cases (nominative, accusative, genitive). These inflections are distinguished through suffixes. The inflection paradigm is summarized in the table below

#+BEGIN_EXPORT html
<table class="para"><tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td class="strong">&empty;</td>
    <td class="strong">-a</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>&empty;</td>
    <td>-sa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td class="weak">-(i)m</td>
    <td class="weak">-(i)da</td>
</tr></tbody></table>
#+END_EXPORT

The (i) in the genitive suffix indicates the fact that for consonant final roots (except those ending in /m/), the suffix is -im while for vowel final roots it is simply -m. An example noun declension is given below

#+BEGIN_EXPORT html
<table class="para">
<caption><i>asi</i> "ruler"</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td>asja</td>
    <td>asjā</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>asi</td>
    <td>asisa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>asim</td>
    <td>asida</td>
</tr></tbody></table>
#+END_EXPORT

However, not all nouns decline in such a straightforward way. The following sets of example paradigms illustrate a few nuances of this declension system.

#+BEGIN_EXPORT html
<div class="holder">
<table class="para">
<caption><i>xwar</i> "iron"</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td>xwar</td>
    <td>xwara</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>xwar</td>
    <td>xwarsa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>xurim</td>
    <td>xurida</td>
</tr></tbody></table>

<table class="para">
<caption><i>rm</i> "animal fat"</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td>ram</td>
    <td>rama</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>rm</td>
    <td>rnsa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>rm</td>
    <td>rnda</td>
</tr></tbody></table>
</div>
#+END_EXPORT

As these examples demonstrate, the different cases have a tendency to collapse in the singular. For strong nouns, the nominative and accusative collapse, while for weak nouns with a final -m, the genitive and accusative collapse.

#+BEGIN_EXPORT html
<div class="holder">
<table class="para">
<caption><i>rsā</i> "Person"</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td>rsā</td>
    <td>rsā</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>rsā</td>
    <td>rsāsa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>rsam</td>
    <td>rsada</td>
</tr></tbody></table>

<table class="para">
<caption><i>cē</i> "mosquito"</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td>cē</td>
    <td>ceja</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>cē</td>
    <td>cēsa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>cem</td>
    <td>ceda</td>
</tr></tbody></table>

<table class="para">
<caption><i>mō</i> "hill"</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</thi could fix her>
    <td>mō</td>
    <td>mowa</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>mō</td>
    <td>mōsa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>mom</td>
    <td>moda</td>
</tr></tbody></table>
</div>
#+END_EXPORT

These three examples show the oddities that can occur with roots ending in a "true" vowel (i.e. not /i/ or /u/). For those ending with /a/ or /ā/, the nominative plural will be the same as the nominative and accusative singular. For those ending with /e/, /ē/, /o/ or /ō/, the singular and plural don't merge, but a glide is inserted to break up the two vowels, and the primary vowel shortens to compensate.

#+BEGIN_EXPORT html
<table class="para">
<caption><i>qa</i> "spear"</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td>qā</td>
    <td>qā</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>qa</td>
    <td>qasa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>qaim</td>
    <td>qada</td>
</tr></tbody></table>
#+END_EXPORT

This example demonstrates some oddities in the genitives of nouns whose final syllable is open and begins with /q/. Since such syllables cannot have a nasal coda, the ending -/im/ is used. In actual pronunciation, this sequence is realized with a glide breaking up the two vowels, i.e. /qaim/ is pronounced [qa.jim].

Lastly, some nouns (almost entirely body parts) have distinct dual forms. These forms are identical to the plurals but with final /o/ instead of /a/, and final /ō/ instead of /ā/.
** Pronouns

Each pronoun has 3 cases (the same as for nouns) and 3 numbers (singular, dual, and plural) for a total of 9 forms. There are 4 separate pronouns for the 1st person, 2nd person, animate 3rd person and inanimate 3rd person. The dual forms of the inanimate 3rd person, while given here by analogy with the animate 3rd person, are unattested in actual use.

#+BEGIN_EXPORT html
<div class="holder">
<table class="para">
<caption><i>ja</i> 1st person</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">du</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td>ja</td>
    <td>jō</td>
    <td>jā</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>ja</td>
    <td>jaso</td>
    <td>jasa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>im</td>
    <td>ido</td>
    <td>ida</td>
</tr></tbody></table>
<table class="para">
<caption><i>bjak</i> 2nd person</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">du</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td>bjak</td>
    <td>bjako</td>
    <td>bjaka</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>bjak</td>
    <td>bjakso</td>
    <td>bjaksa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>bim</td>
    <td>bido</td>
    <td>bida</td>
</tr></tbody></table>
<table class="para">
<caption><i>nge</i> 3nd person animate</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">du</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td>ngē</td>
    <td>ngejo</td>
    <td>ngeja</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>nge</td>
    <td>ngeso</td>
    <td>ngesa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>ngem</td>
    <td>ngedo</td>
    <td>ngeda</td>
</tr></tbody></table>
<table class="para">
<caption><i>le</i> 3nd person inanimate</caption>
<tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">du</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">nom</th>
    <td>lē</td>
    <td>*lejo</td>
    <td>leja</td>
</tr><tr>
    <th scope="row">acc</th>
    <td>le</td>
    <td>*leso</td>
    <td>lesa</td>
</tr><tr>
    <th scope="row">gen</th>
    <td>lem</td>
    <td>*ledo</td>
    <td>leda</td>
</tr></tbody></table>
</div>
#+END_EXPORT

In addition to these independent forms, there are also clitic forms of the nominative pronouns, whose use is explained in the following section.

#+BEGIN_EXPORT html
<table class="para"><tbody><tr class="head">
    <th></th>
    <th scope="col">sg</th>
    <th scope="col">du</th>
    <th scope="col">pl</th>
</tr><tr>
    <th scope="row">1</th>
    <td>ja-</td>
    <td>jo-</td>
    <td>ja-</td>
</tr><tr>
    <th scope="row">2</th>
    <td>bak-</td>
    <td>bako-</td>
    <td>baka-</td>
</tr><tr>
    <th scope="row">3anim</th>
    <td>nge-</td>
    <td>ngo-</td>
    <td>nga-</td>
</tr><tr>
    <th scope="row">3inan</th>
    <td>le-</td>
    <td>*lo-</td>
    <td>la-</td>
</tr></tbody></table>
#+END_EXPORT

** TODO Verbs

Verbs have 4 finite forms. These are the perfective, past imperfective, non-past imperfective, and imperative. Verbs are split into those with inherent perfective aspect and those with inherent imperfective aspect. Imperfective verbs encompass stative verbs and atelic active verbs, while telic active verbs are perfective. For most verbs telicity is a constant property of the word, but for some verbs (mostly verbs of motion) their telicity and thus their inherent aspect depends on whether they are used intransitively (as in "he walks") or transitively (as in "he walks to the city"), with the former being atelic and thus imperfective and the latter being telic and thus perfective. 

The inflection patterns and the semantics of some of the inflections for these two categories are different as will be seen below.

#+BEGIN_EXPORT html
<div class="holder">
<table class="para">
<caption>Perfective</caption>
<tbody><tr>
    <th scope="row">pfv</th>
    <td>&empty;</td>
</tr><tr>
    <th scope="row">npst ipfv</th>
    <td>-ja</td>
</tr><tr>
    <th scope="row">pst ipfv</th>
    <td>na-...-ja</td>
</tr><tr>
    <th scope="row">imp</th>
    <td class="strong">-ra</td>
</tr></tbody></table>
<table class="para">
<caption>Imperfective</caption>
<tbody><tr>
    <th scope="row">pfv</th>
    <td>-i</td>
</tr><tr>
    <th scope="row">pres ipfv</th>
    <td>&empty;</td>
</tr><tr>
    <th scope="row">pst ipfv</th>
    <td>na-</td>
</tr><tr>
    <th scope="row">imp</th>
    <td class="strong">-ira</td>
</tr></tbody></table>
</div>
#+END_EXPORT

example paradigms are provided below for a perfective verb and an imperfective verb

#+BEGIN_EXPORT html
<div class="holder">
<table class="para">
<caption><i>su</i> "say"</caption>
<tbody><tr>
    <th scope="row">pfv</th>
    <td>su</td>
</tr><tr>
    <th scope="row">npst ipfv</th>
    <td>suja</td>
</tr><tr>
    <th scope="row">pst ipfv</th>
    <td>nasuja</td>
</tr><tr>
    <th scope="row">imp</th>
    <td>swara</td>
</tr></tbody></table>
<table class="para">
<caption><i>xak</i> "know"</caption>
<tbody><tr>
    <th scope="row">pfv</th>
    <td>xaki</td>
</tr><tr>
    <th scope="row">npst ipfv</th>
    <td>xak</td>
</tr><tr>
    <th scope="row">pst ipfv</th>
    <td>naxak</td>
</tr><tr>
    <th scope="row">imp</th>
    <td>xakira</td>
</tr></tbody></table>
</div>
#+END_EXPORT

*** Perfective

 The perfective is used for an event viewed as a simple whole without internal structure. On its own it most commonly has past tense meaning, though it may also be used for narrating events as they happen in the present or for simple future events which have a definite time expressed by an adverbial phrase. Future events without an adverbial phrase expressing a time dont use any of the finite verb forms, and will be discussed later.

 For verbs with inherent imperfective aspect, the perfective generally indicates the beginning of the atelic action or the state which the verb describes, thus /ngaxaki/ would mean (keeping in mind the caveats about tense given above) "they began to know" or more idiomatically "they learned". A special case of this is for verbs which express spatial configuration such as /krgr/ "to be scattered", for which the perfect expresses movement into that state, as in /ngakrgir/ "they scattered." The perfective form of an imperfective verb can also have the imperfective suffix -/ja/ added on top of the eprfective suffix -/i/ to convey the start of the state or action as an ongoing event of its own, as in /ngakrgirja/ "they are scattering" 

*** Past Imperfective

 The past imperfective is used for actions viewed as ongoing which ended in the past.

*** Non-Past Imperfective

 The non-past imperfective is most commonly used to express ongoing actions which began in the past and continue through the present. Like the perfective, it may also have future meaning if used with an adverbial expressing a specific time. The default meaning of the future use of the non-past imperfective is that the start of the action is in the future but before the time which is specified, however it is also possible to express that an action which started in the past will still be ongoing in the future by adding the particle /la/ after the verb.

*** Imperative

 The imperative can be used without an explicit subject to give commands, with the same form being used regardless of the number of people being addressed, as in /oxadō/ "kneel". The imperative form may also be used with an explicit subject to express optative meaning as in /ngawoxadō ngada sam bim/ "may they kneel before you."

*** Oddities

 Some intransitive verbs expressing spatial configuration such as /oxado/ "to be kneeling" are derived from prepositional phrases involving body parts, and so are followed by a genitive pronoun that matches the subject, as in /ngejoxado ngem/ "he is kneeling," historically from /ngejo kado ngem/ "he is on his two knees." Any verb endings will attach to the verb rather than to the genitive pronoun, so "she knelt" would be translated as /ngejoxadowi ngem/ and not /*ngejoxado ngemi/ 

* TODO Derivational Morphology

* TODO Syntax

** Prepositions

All adpositions are prepositions. Most prepositions expressing motion take their objects in the accusative, while those expressing static location take their object in the genitive. An exception to this is prepositions of motion which are historically derived from compounds of another preposition with a term for a body part, which take genitive objects.

** Sentence Structure

The basic structure of all sentences is [topic][comment]
   
*** Nominal and Prepositional Predicate Sentences

Sentences with a nominal predicate (i.e. of the form "A is B") and a pronominal subject are formed by attaching the clitic form of the pronoun to the nominative case of the predicate, as in /jāsja/ "I am a/the ruler." For those with a nominal subject, the subject is placed at the beginning followed by the 3rd person pronominal form of the sentence, as in /xansā ngejasja/ "Xansa is a/the ruler." This is in contrast to simply juxtaposing two nominative case nouns which is how apposition is expressed, as in /xansā asja/ "Xansa the ruler."

Sentences with a prepositional phrase as the predicate are formed in the same way, with a prepositional phrase appearing in the position of the nominal predicate.



* Lexicon
** Nouns
*** Natural World
  - /mr/ :: soil
  - /mō/ :: hill
  - /u/ :: water
*** Plants and Fungi
*** Animals
  - /cē/ :: mosquito
  - /fā/ :: pig
*** People
  - /rsā/ :: person
  - /asi/ :: ruler
*** Body Parts
  - /ka/ :: knee
*** Material Culture
  - /xwar/ :: iron
  - /qa/ :: spear
  - /rm/ :: animal fat (e.g. lard)
** Verbs
*** Sound Emissions
 - /su/ :: say
*** Mental States
 - /xak/ :: know
*** Spatial states
 - /krgr/ :: to be strewn about or scattered
** Prepositions
 - /o/ :: on
 - /sam/ :: in the presence of, before
 


 
